# Generated by Django 4.2.3 on 2023-08-31 10:43

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "cidade",
                    models.CharField(
                        choices=[
                            (" a. dourada", " A. Dourada"),
                            (" camaçari", " Camaçari"),
                            (" candeal", " Candeal"),
                            (" capim grosso", " Capim Grosso"),
                            (" iaçu", " Iaçu"),
                            (" ibitiara", " Ibitiara"),
                            (" ibotirama", " Ibotirama"),
                            (" iuiu", " Iuiu"),
                            (" jacobina", " Jacobina"),
                            (" pindobaçu", " Pindobaçu"),
                            (" salvador", " Salvador"),
                            (" saúde", " Saúde"),
                            (" seabra", " Seabra"),
                            (" serrolândia", " Serrolândia"),
                            (" sobradinho", " Sobradinho"),
                            (" utinga", " Utinga"),
                            (" várzea nova", " Várzea Nova"),
                            (" aracaju", " Aracaju"),
                            (" campo do brito", " Campo do Brito"),
                            (" carira", " Carira"),
                            (" frei paulo", " Frei Paulo"),
                            (" macambira", " Macambira"),
                            (" n. sª da glória", " N. Sª Da Glória"),
                            (" neópolis", " Neópolis"),
                            (" simão dias", " Simão Dias"),
                            (" são cristóvão", " São Cristóvão"),
                        ],
                        default=" ",
                        max_length=100,
                    ),
                ),
                (
                    "operacao",
                    models.CharField(
                        choices=[
                            ("emprestimo", "Empréstimo"),
                            ("consorcio", "Consórcio"),
                            ("conta", "Conta Corrente"),
                            ("outros", "Outros"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "telefone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region="BR"
                    ),
                ),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
