# Generated by Django 4.2.3 on 2023-09-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("piemonte", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=100)),
                ("rg", models.IntegerField()),
            ],
        ),
    ]
