# Generated by Django 4.2.3 on 2023-09-05 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("piemonte", "0002_cliente"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="data_contrato",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="cliente",
            name="duracao_contrato",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cliente",
            name="nmr_contrato",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cliente",
            name="operacao",
            field=models.CharField(
                choices=[
                    ("emprestimo", "Empréstimo"),
                    ("consorcio", "Consórcio"),
                    ("conta", "Conta Corrente"),
                    ("outros", "Outros"),
                ],
                default=" ",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="cliente", name="rg", field=models.CharField(max_length=10),
        ),
    ]
