# Generated by Django 4.2.3 on 2023-09-05 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("piemonte", "0004_alter_cliente_nmr_contrato"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="data_nascimento",
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="cliente",
            name="sexo",
            field=models.CharField(
                blank=True,
                choices=[("masculino", "Masculino"), ("feminino", "Feminino")],
                max_length=10,
                null=True,
            ),
        ),
    ]
